version: 1
disable_existing_loggers: false
formatters:
  text:
    format: "%(asctime)s | %(name)s | %(levelname)s | %(module)s:%(lineno)d | %(message)s"
  colored:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s%(name)s | %(module)s:%(lineno)d | %(message)s"
    log_colors:
      DEBUG: bold_blue
      INFO: bold_green
      WARNING: bold_yellow
      ERROR: bold_red
      CRITICAL: bold_red,bg_white
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
loggers:
  root:
    level: DEBUG
    handlers: [console]
  sqlalchemy.engine.Engine:
    level: WARNING
    handlers: [console]
  database.db:
    level: WARNING
    handlers: [console]

  tasks:
    level: DEBUG
    handlers: [console]

  # uvicorn
  uvicorn.access:
    level: INFO
    handlers: [console]
  uvicorn.error:
    level: ERROR
    handlers: [console]


